services:
  scylladb:
    image: 'scylladb/scylla:5.2.0'
    container_name: scylladb
    ports:
      - 7001:7001
      - 9042:9042
      - 9142:9142
    environment:
      - SCYLLA_SEED=scylladb
      - SCYLLA_CLUSTER_NAME=CC6240
      - SCYLLA_USER=admin
      - SCYLLA_PASSWORD=admin
    volumes:
      - ./data/scylladb:/var/lib/scylla
    networks:
      - cc6240

networks:
  cc6240:

